name: Node CI

on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "Wallash"
          user-email: "alexandre.vauthier@edu.devinci.fr"
          message: "Automatically built typescript"
          directories: ./src

